### ISSUE TITLE
Making this library router agnostic and only dependent on `history`

### ISSUE THREAD

**Issue by johanneslumpe** [johanneslumpe/redux-react-router-transitions#2]
With the advent of `react-router` 1.0 there have been great API improvements. For this project the main part is that the user can now provide a `history` instance to the router. Since the `history` object is not specific to `react-router` and can be used with any type of router, the current library name isn't fitting anymore. I am proposing to rename this from `redux-react-router-transitions` to `redux-history-transitions` in order to make clear that this library works with any system which uses a `history` instance to manage url-state.

Furthermore the use of `history` introduces breaking changes. Originally you were able to return an object with a shape of `{ path, params, query, replace }` and the library would then utilize `react-router` to merge `params` into `path` and append `query` as query-string.

This shape has changed and now looks like this: `{ path, query, replace, state }`. This means that instead of returning a path like `/some/path/:myParam`, you now will use template strings to inject the params directly: `/some/path/${myParamVar}`. In order to use query strings, you will have to enhance the `history` object with the `useQueries` enhancer. How this works can be seen in the example project.

All in all what this means is that `redux-history-transitions` now can be used whether you are using `react` or `angular` or whatever view library/framework you prefer, as long as you use `history` to manage your urls. This also means that I will be dropping support for `react-router` 0.13

The code in the master branch is updated and a working example is provided.

I would love to hear some opinions about this (suggestions to improve the API are also welcome!).
I personally feel that this is the way to go.

/cc @gaearon @idolize

**Comment by tappleby** [comment]
I wasnt familiar with the previous API but anytime you can minimize dependencies (without breaking DX) its a good thing!

I prefer the more explicit `/some/path/${myParamVar}` paths as well.

**Comment by johanneslumpe** [comment]
I just went ahead and did this - closing, but feel free to still comment on it!

**Comment by idolize** [comment]
I think this is a great idea! It's cool to see `react-router` and the surrounding ecosystem become more loosely coupled in general; it gives devs more control over their application routing and state.
