### ISSUE TITLE
Warning: [history] pushState is deprecated; use push instead

### ISSUE THREAD

**Issue by hannupekka** [johanneslumpe/redux-react-router-transitions#4]
Should replace `pushState` & `replaceState` with `push` & `replace` (deprecated in https://github.com/rackt/history/blob/master/CHANGES.md#v1140) and use location descriptor as shown here: https://github.com/rackt/history#basic-usage

I can provide pull request on monday if someone does not beat me to it.

**Comment by johanneslumpe** [comment]
Published fix as version 2.0
