### ISSUE TITLE
Async action

### ISSUE THREAD

**Issue by aoshi321** [johanneslumpe/redux-react-router-transitions#6]
Hi 

Is this able to handle an async action?

thanks

**Comment by johanneslumpe** [comment]
@aoshi321 Yes. You get the action passed to the transition handler and you can inspect it. So if you for example add a `meta` object to the action, which has a `done` prop, then you can set it to `true` when the async action is completed. You can use that field to determine whether to return a transition value or not.

**Comment by aoshi321** [comment]
Is it possible you can show me a quick example ?

thx
